server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///E:/personal-development/spring-boot-projects/microservices-spring-boot-postgres/config-server/src/main/resources/config/customer-service